// 简体中文词表。key 是 `L(…)` 里的英文原句,**逐字**(含标点与 `{0}` 占位符)。
//
// 守卫(`internal/cli/macos_menu_l10n_test.go`)钉住三件事:源码里每一个 `L("…")`
// 在这里都有译文;这里每一条都还有人用;两边的占位符一一对应。
// 这是 Sources 里唯一允许出现中文的非注释位置。
//
// 用语:protection 译「保护」、tunnel 译「隧道」、direct 译「直连」、
// rule 译「规则」、server 译「服务器」、Core / Guardian 不译(日志与命令里就是这两个词)。
/// Language 子菜单里这一项的名字。用它自己的文字写,不随界面语言变。
let simplifiedChineseEndonym = "简体中文"

let zhHansTranslations: [String: String] = [
    "Follow System": "跟随系统",
    "Bypasses the tunnel": "不经过隧道",
    "Forced through the tunnel": "强制经过隧道",
    "Guardian not responding; protection may still be on": "Guardian 没有应答；保护可能仍在生效",
    "Status socket unavailable": "状态 socket 不可用",
    "Needs attention": "需要处理",
    "Protection": "保护",
    "{0} failed · {1} warning · {2} not checked": "{0} 项失败 · {1} 项警告 · {2} 项未检查",
    "{0} failed · {1} warnings · {2} not checked": "{0} 项失败 · {1} 项警告 · {2} 项未检查",
    "Failed": "失败",
    "Warning": "警告",
    "Not checked": "未检查",
    "OK": "正常",
    "Info": "信息",
    "Checked at {0}": "检查于 {0}",
    "maintenance": "维护",
    "updating bx": "正在更新 bx",
    "updating bx, migrated from an older upgrade record": "正在更新 bx（沿用旧版升级留下的记录）",
    "Paused for {0} — up to {1} min": "已暂停（{0}）—— 最多 {1} 分钟",
    "Off": "已关闭",
    "Paused": "已暂停",
    "Handled by bx ({0})": "由 bx 处理（{0}）",
    "Handled by bx": "由 bx 处理",
    "Handled by bx (data plane)": "由 bx 处理（数据面）",
    "Not managed": "未接管",
    "DNS not managed": "DNS 未被接管",
    "Status unavailable": "状态不可用",
    "DNS status unavailable": "DNS 状态不可用",
    "Guardian connection failed ({0}).": "连接 Guardian 失败（{0}）。",
    "Guardian returned an invalid response.": "Guardian 返回了无效的应答。",
    "Guardian response exceeded its safety limit.": "Guardian 的应答超出了安全上限。",
    "Guardian returned a non-JSON response.": "Guardian 返回的不是 JSON。",
    "Guardian request failed ({0}).": "Guardian 请求失败（{0}）。",
    "Guardian request failed ({0}, code={1}).": "Guardian 请求失败（{0}，code={1}）。",
    "bx is protected again": "bx 已恢复保护",
    "The tunnel is back. Traffic is flowing through bx.": "隧道已恢复，流量重新经过 bx。",
    "bx needs attention": "bx 需要处理",
    "Protection could not be restored on its own. Open the bx menu for details.": "保护没能自动恢复。打开 bx 菜单查看详情。",
    "bx: tunnel is down": "bx：隧道已断开",
    "The tunnel has been down for a while. bx is blocking traffic so nothing leaks (kill-switch).": "隧道已经断开一段时间。bx 正在拦截流量，确保不会泄漏（kill-switch）。",
    "bx: traffic blocked": "bx：流量已被拦截",
    "Protection is on but the tunnel is unavailable. bx is blocking traffic so nothing leaks (kill-switch).": "保护开着，但隧道不可用。bx 正在拦截流量，确保不会泄漏（kill-switch）。",
    "Routing Rules": "分流规则",
    "Presets": "预设",
    "Add Rule…": "添加规则…",
    "Show Config": "显示配置文件",
    "Remove": "删除",
    "Removed {0}": "已删除 {0}",
    "Undo": "撤销",
    "Hide": "收起",
    "Show": "展开",
    "Enter the server address (an IP, a hostname, or an ssh_config alias).": "请输入服务器地址（IP、主机名或 ssh_config 里的别名）。",
    "The address cannot contain spaces, quotes, or @ — put the login name in the User field.": "地址里不能有空格、引号或 @ —— 登录名请填在登录名那一栏。",
    "Enter the SSH login name (usually root).": "请输入 SSH 登录名（通常是 root）。",
    "The login name cannot contain spaces, quotes, or @.": "登录名里不能有空格、引号或 @。",
    "The name is too long (64 characters maximum).": "名字太长了（最多 64 个字符）。",
    "The name may only contain letters, digits, and . _ -": "名字只能包含英文字母、数字和 . _ -",
    "<server address>": "<服务器地址>",
    "bx is about to install a server on {0} over ssh.": "bx 即将通过 ssh 在 {0} 上安装服务端。",
    "Your SSH password or key is handled by ssh itself — bx never sees it.": "SSH 密码或密钥由 ssh 自己处理 —— bx 看不到它们。",
    "bx never handles your SSH password or key. The command runs in Terminal, where ssh asks for whatever it needs.": "bx 从不经手你的 SSH 密码或密钥。命令在「终端」里运行，ssh 需要什么会自己问你。",
    "Older build; live Core status and diagnostics archive unavailable": "旧版本：拿不到 Core 的实时状态，也无法生成诊断包",
    "Diagnostics archive unavailable": "无法生成诊断包",
    "To finish updating, run: {0}": "要完成更新，请运行：{0}",
    "Set Up a New Server": "部署新服务器",
    "Server address — 1.2.3.4 or an ssh_config alias": "服务器地址 —— 1.2.3.4 或 ssh_config 里的别名",
    "SSH login": "SSH 登录名",
    "Name it in your list (optional)": "在列表里给它起个名字（可选）",
    "Your current exit does not change. bx never sees your SSH password.": "你当前的出口不会改变。bx 看不到你的 SSH 密码。",
    "Open in Terminal": "在终端中打开",
    "Install bx…": "安装 bx…",
    "Update bx…": "更新 bx…",
    "{0} installed · Guardian switch pending": "已安装 {0} · 等待切换 Guardian",
    "Updating bx…": "正在更新 bx…",
    "Turn Off bx": "关闭 bx",
    "Repair bx…": "修复 bx…",
    "Uninstall bx…": "卸载 bx…",
    "Uninstall bx?": "卸载 bx？",
    "bx will stop protection and remove its background service, the menu bar app, and the bx command. Your network returns to how it was before bx.\n\nYour connection settings are kept, so reinstalling does not need the link again. macOS will ask for administrator authorization.": "bx 会停止保护，并删除它的后台服务、菜单栏 App 和 bx 命令。你的网络会回到装 bx 之前的样子。\n\n连接设置会保留，重新安装时不必再贴一次链接。macOS 会要求管理员授权。",
    "Uninstall": "卸载",
    "Uninstall failed": "卸载失败",
    "bx could not finish uninstalling. Protection may still be running.\n\nYou can finish it from Terminal:\n    sudo bx uninstall": "bx 没能完成卸载，保护可能仍在运行。\n\n你可以在终端里完成它：\n    sudo bx uninstall",
    "Diagnostics": "诊断",
    "Checks": "检查",
    "Logs": "日志",
    "This version of bx Guardian does not provide checks.": "这一版 bx Guardian 不提供检查。",
    "No checks yet.": "还没有检查过。",
    "Check Now": "立即检查",
    "Asks bx to check now. This probes your server once, outside the tunnel.": "让 bx 立即检查一次。这会在隧道之外探测一次你的服务器。",
    "This version of bx Guardian does not provide logs.": "这一版 bx Guardian 不提供日志。",
    "No logs loaded yet.": "还没有载入日志。",
    "Load Logs": "载入日志",
    "Reads the tail of bx's own logs.": "读取 bx 自己日志的末尾。",
    "Run Again": "再检查一次",
    "Asks bx to check again. This probes your server once, outside the tunnel.": "让 bx 再检查一次。这会在隧道之外探测一次你的服务器。",
    "Highlighting lines that mention {0}.": "正在高亮提到 {0} 的行。",
    "Not available: {0}": "不可用：{0}",
    "This log is empty.": "这份日志是空的。",
    "Export Diagnostics…": "导出诊断信息…",
    "Runs bx doctor in Terminal and collects a diagnostics folder you can share.": "在终端里运行 bx doctor，收集一个可以分享的诊断文件夹。",
    "Servers": "服务器",
    "Currently using": "正在使用",
    "Other servers": "其他服务器",
    "Testing…": "测试中…",
    "Test All": "全部测速",
    "Measures the round trip from this Mac to each server, outside the tunnel.": "在隧道之外测量这台 Mac 到每台服务器的往返延迟。",
    "Exit IP": "出口 IP",
    "Asks a public service where your traffic appears to come from.": "问一个公共服务：你的流量看起来是从哪里出来的。",
    "Set Up a New VPS…": "部署新 VPS…",
    "Install bx server on a fresh VPS over SSH.": "通过 SSH 在一台全新的 VPS 上安装 bx 服务端。",
    "Add Existing Server…": "添加已有服务器…",
    "Paste a bx link to add a server and switch to it. The previous server stays in the list.": "粘贴一条 bx 链接，添加一台服务器并切换过去。原来那台仍留在列表里。",
    "Carrying your traffic now (confirmed by bx)": "正在承载你的流量（bx 已确认）",
    "Not confirmed as carrying your traffic right now": "没能确认它此刻在承载你的流量",
    "Switching…": "切换中…",
    "Use": "使用",
    "More actions for {0}": "{0} 的更多操作",
    "Replace Link…": "更换链接…",
    "Remove…": "删除…",
    "Switch to another server first, then you can remove this one.": "先切换到另一台服务器，才能删除这一台。",
    "Traffic by App": "按应用查看流量",
    "Quit bx…": "退出 bx…",
    "bx will stop protecting system traffic, restore managed DNS settings, and close this menu. To start bx again, open Bx.app from Applications.": "bx 会停止保护系统流量、还原它接管的 DNS 设置，并关闭这个菜单。要再次启动 bx，请从「应用程序」里打开 Bx.app。",
    "Update bx?": "更新 bx？",
    "Internet access may pause briefly. bx will reconnect automatically.": "网络可能会短暂中断，bx 会自动重新连接。",
    "bx is up to date": "bx 已是最新版本",
    "Update couldn't be completed. Previous version restored.": "更新没能完成，已恢复到之前的版本。",
    "Update couldn't be completed: during the switch the new version could not bring up the tunnel. That points at your server or the path to it, not the update itself. Previous version restored — try updating again later.": "更新没能完成：切换时新版本没能建立隧道。这说明问题出在你的服务器或通往它的线路上，而不是这次更新本身。已恢复到之前的版本 —— 稍后再试一次更新。",
    "Update couldn't be completed: the new version could not start on this Mac. Previous version restored.": "更新没能完成：新版本没能在这台 Mac 上启动。已恢复到之前的版本。",
    "Version: {0}": "版本：{0}",
    "Version: {0} → {1} available": "版本：{0} → 有新版 {1}",
    "Installing… the network pauses for a few seconds ({0}s)": "正在安装… 网络会中断几秒（{0} 秒）",
    "Downloading — {0}": "正在下载 —— {0}",
    "Downloading… {0}s": "正在下载… {0} 秒",
    "Downloading and installing — {0}": "正在下载并安装 —— {0}",
    "Downloading and installing… {0}s": "正在下载并安装… {0} 秒",
    "Waiting for Guardian": "等待 Guardian",
    "Checking network path": "正在检查网络路径",
    "Validating protected path": "正在验证受保护的路径",
    "Rebinding network path": "正在重新绑定网络路径",
    "Checking protected transport": "正在检查受保护的传输",
    "Applying protected path": "正在应用受保护的路径",
    "Verifying protection": "正在验证保护",
    "Reconnecting protected path": "正在重连受保护的路径",
    "Can't reach the server — cafés and hotels often need sign-in first": "连不上服务器 —— 咖啡馆和酒店的网络常常要先登录",
    "Protected path changed": "受保护的路径变了",
    "Protected path unavailable": "受保护的路径不可用",
    "Network unavailable": "网络不可用",
    "Recovery canceled": "恢复已取消",
    "Recovery unavailable": "无法恢复",
    "Recovery was replaced": "恢复被新的一次取代",
    "Protected transport unavailable": "受保护的传输不可用",
    "Could not rebind network path": "没能重新绑定网络路径",
    "Network path unavailable": "网络路径不可用",
    "Protection verification failed": "保护验证失败",
    "Recovery failed": "恢复失败",
    "Reconnecting": "正在重连",
    "Reconnected": "已重连",
    "Blocked": "已拦截",
    "Reconnect Failed": "重连失败",
    "Recovery": "恢复",
    "Unrecognized recovery state ({0})": "认不出的恢复状态（{0}）",
    "Route": "路由",
    "Latency": "延迟",
    "Outside bx": "绕过 bx",
    "DNS": "DNS",
    "Direct lookups": "直连解析",
    "UDP Relay": "UDP 转发",
    "Via": "线路",
    "Maintenance": "维护",
    "{0} ms": "{0} ms",
    "Tunnel unhealthy": "隧道不健康",
    "{0} — quit and reopen": "{0} —— 请退出后重新打开",
    "Settling": "退场中",
    "1 connection from before protection was on — it moves into bx as the app reconnects": "1 条保护开启前的连接仍在 bx 外 —— 应用重连后自动进入",
    "{0} connections from before protection was on — they move into bx as apps reconnect": "{0} 条保护开启前的连接仍在 bx 外 —— 应用重连后自动进入",
    "Through the tunnel": "经过隧道",
    "Direct": "直连",
    "Not collecting app traffic right now.": "此刻没有在采集应用流量。",
    "Couldn't read app traffic: {0}": "读不到应用流量：{0}",
    "No matches": "没有匹配项",
    "No app traffic seen yet.": "还没有看到应用流量。",
    "Unknown app": "未知应用",
    "…and {0} more": "…还有 {0} 个",
    "Always direct: {0}": "总是直连：{0}",
    "Always through tunnel: {0}": "总是经过隧道：{0}",
    "App": "应用",
    "Conns": "连接",
    "Up/s": "上行/秒",
    "Down/s": "下行/秒",
    "Up": "上行",
    "Down": "下行",
    "Rule": "规则",
    "Byte counts are approximate: ports get reused, and an app listed in two sections may show all its bytes on one side.": "字节数是近似值：端口会被复用，出现在两个分组里的应用可能把全部字节都算在其中一边。",
    "Right-click an app to always send one of its destinations direct or through the tunnel.": "右键点一个应用，可以让它的某个目的地总是直连或总是经过隧道。",
    "Not updating — this is the last report bx could read. Protection may be off.": "没有在更新 —— 这是 bx 最后一次读到的报告。保护可能已经关了。",
    "bx answered with an error (HTTP 500, code={0}). Use Show Details for the reason.": "bx 返回了错误（HTTP 500，code={0}）。点「显示详情」查看原因。",
    "bx answered with an error (HTTP 500, code={0}). bx recorded the reason in its log.": "bx 返回了错误（HTTP 500，code={0}）。原因已记在 bx 的日志里。",
    "bx answered with an error (HTTP 500). Use Show Details for the reason.": "bx 返回了错误（HTTP 500）。点「显示详情」查看原因。",
    "bx answered with an error (HTTP 500). bx recorded the reason in its log.": "bx 返回了错误（HTTP 500）。原因已记在 bx 的日志里。",
    "bx answered HTTP {0} (code={1}).": "bx 返回了 HTTP {0}（code={1}）。",
    "bx answered HTTP {0}.": "bx 返回了 HTTP {0}。",
    "The menu could not fetch this from bx: {0}": "菜单没能从 bx 取到这些内容：{0}",
    "The menu could not fetch this from bx, and the reason was not recorded.": "菜单没能从 bx 取到这些内容，原因没有被记录下来。",
    "{0} of {1} connections failed ({2}%) — this path is not working": "{1} 次连接里失败了 {0} 次（{2}%）—— 这条路不通",
    "bx flagged this rule, and this version could not say why.": "bx 标记了这条规则，但这一版说不出原因。",
    "bx flagged this rule ({0}).": "bx 标记了这条规则（{0}）。",
    "A rule with nothing written under it here has not been checked: this version of bx did not check these rules for problems.": "下面没写任何说明的规则并不是检查过没问题：这一版 bx 没有检查这些规则。",
    "A rule with nothing written under it here has not been checked: bx's core is not answering, so it could not say which rules are failing.": "下面没写任何说明的规则并不是检查过没问题：bx 的 Core 没有应答，说不出哪些规则在失败。",
    "A rule with nothing written under it here has not been checked: this version of bx did not check these rules for problems, and bx's core is not answering, so it could not say which rules are failing.": "下面没写任何说明的规则并不是检查过没问题：这一版 bx 没有检查这些规则，而且 bx 的 Core 没有应答，说不出哪些规则在失败。",
    "Enter a domain, for example *.example.com": "请输入一个域名，例如 *.example.com",
    "Domains cannot contain spaces": "域名里不能有空格",
    "Leave out the quotes — bx adds them itself": "不用加引号 —— bx 会自己加",
    "{0} is not a domain": "{0} 不是一个域名",
    "Anyone can register a subdomain on this platform, and a bx direct rule covers every subdomain of what you write — so a stranger could make your real IP leave outside the tunnel. Writing a deeper host narrows this but does not remove it. Use Add Anyway only if you control that host.": "任何人都能在这个平台上注册子域名，而 bx 的直连规则会覆盖你写的域名下的所有子域名 —— 于是一个陌生人就能让你的真实 IP 在隧道之外发出去。写一个更深一层的主机名能缩小范围，但去不掉这个风险。只有在你自己掌控那台主机时才点「仍然添加」。",
    "{0} failed": "{0} 项失败",
    "Your traffic leaves from {0} today.": "你的流量目前从 {0} 出去。",
    "After this change it will leave from the server in the link you just provided.": "改完之后，流量会从你刚提供的链接里的那台服务器出去。",
    "The link was read from your clipboard.": "这条链接是从剪贴板里读到的。",
    "bx reconnects to apply it.": "bx 会重新连接以应用它。",
    "Game downloads and cloud saves come straight from the CDN": "游戏下载与云存档直接从 CDN 获取",
    "iCloud sync, Game Center and the App Store stay responsive": "iCloud 同步、Game Center 与 App Store 保持流畅",
    "WeChat, Tencent Meeting and QQ sign-in, chat and media": "微信、腾讯会议与 QQ 的登录、聊天和媒体",
    "Chinese apps, video and shopping load from nearby servers": "国内应用、视频与购物从就近的服务器加载",
    "{0} domains": "{0} 个域名",
    "Your own rules ({0}) — global mode: these are the only domains that go direct": "你自己的规则（{0}）—— 全局模式：只有这些域名走直连",
    "Your own rules ({0}) — split mode: exceptions on top of the built-in China list": "你自己的规则（{0}）—— 分流模式：在内置中国列表之上的例外",
    "Your own rules ({0})": "你自己的规则（{0}）",
    "Connecting": "正在连接",
    "Disconnecting": "正在断开",
    "{0}… {1}s": "{0}… {1} 秒",
    "Taking longer than usual — this normally finishes within about 3 seconds": "比平时久 —— 通常 3 秒左右就能完成",
    "Will quit once the current operation finishes": "当前操作完成后就会退出",
    "Full reason: {0}": "完整原因：{0}",
    "bx could not start: bx cannot reach {0} — no TCP connection was established to that address.": "bx 没能启动：bx 连不上 {0} —— 与那个地址之间一次 TCP 连接都没建立起来。",
    "bx could not start: bx cannot reach your server — no TCP connection was established to that address.": "bx 没能启动：bx 连不上你的服务器 —— 与那个地址之间一次 TCP 连接都没建立起来。",
    "That machine may be down or may have changed IP, but this Mac's own network could be at fault too.": "那台机器可能挂了或换了 IP，但也可能是这台 Mac 自己的网络有问题。",
    "bx could not start: {0} is answering on TCP, but the tunnel did not come up within the start-up window.": "bx 没能启动：{0} 在 TCP 上有应答，但隧道没能在启动时限内建立起来。",
    "bx could not start: your server is answering on TCP, but the tunnel did not come up within the start-up window.": "bx 没能启动：你的服务器在 TCP 上有应答，但隧道没能在启动时限内建立起来。",
    "That machine is alive — look at the link, its credentials, the SNI, or interference on the way, not at whether the server is down.": "那台机器是活着的 —— 该查的是链接、它的凭据、SNI 或途中的干扰，而不是服务器有没有挂。",
    "bx could not start: the tunnel did not come up, and bx could not tell whether that server is still there — it runs a UDP transport (hysteria2/QUIC), which a single TCP probe cannot observe.": "bx 没能启动：隧道没建立起来，bx 也判断不了那台服务器还在不在 —— 它用的是 UDP 传输（hysteria2/QUIC），一次 TCP 探测看不到它。",
    "To confirm that machine is alive, try ping or ssh to {0}": "要确认那台机器还活着，试试 ping 或 ssh 到 {0}",
    "To confirm that machine is alive, try ping or ssh to it": "要确认那台机器还活着，试试 ping 或 ssh 到它",
    "bx could not start: the tunnel did not come up, and bx could not tell whether {0} is still there — its probe failed on this Mac before any SYN left it.": "bx 没能启动：隧道没建立起来，bx 也判断不了 {0} 还在不在 —— 探测在这台 Mac 上就失败了，一个 SYN 都没发出去。",
    "bx could not start: the tunnel did not come up, and bx could not tell whether that server is still there — its probe failed on this Mac before any SYN left it.": "bx 没能启动：隧道没建立起来，bx 也判断不了那台服务器还在不在 —— 探测在这台 Mac 上就失败了，一个 SYN 都没发出去。",
    "Check bx's own direct route first (the signature of the 2026-08-13 failure): route -n get -ifscope <your interface> 1.1.1.1 — if it says \"not in table\", bx's own direct dialer on this Mac is broken and switching servers will not help.": "先检查 bx 自己的直连路由（2026-08-13 那次故障的特征）：route -n get -ifscope <你的网卡> 1.1.1.1 —— 如果它说 \"not in table\"，就是这台 Mac 上 bx 自己的直连出了问题，换服务器没有用。",
    "If the route is there, this Mac most likely cannot resolve that server's host name — for that one, switching servers does help.": "如果那条路由在，多半是这台 Mac 解析不了那台服务器的主机名 —— 这种情况换一台服务器确实有用。",
    "bx could not start: the tunnel did not come up, and bx could not tell whether that server is still there (the check itself did not complete).": "bx 没能启动：隧道没建立起来，bx 也判断不了那台服务器还在不在（检查本身没有完成）。",
    "To check the server yourself: {0}": "自己检查服务器：{0}",
    "Check that the server link in the configuration is still right": "检查配置里的服务器链接是否仍然正确",
    "bx could not start: something in the configuration is unusable (a rule, a CIDR, a hosts entry, or a server link). After editing it, run sudo bx down && sudo bx up.": "bx 没能启动：配置里有东西用不了（某条规则、某个 CIDR、某条 hosts 或某条服务器链接）。改完之后运行 sudo bx down && sudo bx up。",
    "bx could not start: it could not read its configuration file — most likely bx has not been set up on this Mac yet, or the file is not readable. To set it up: sudo bx setup <your link>.": "bx 没能启动：它读不到自己的配置文件 —— 多半是这台 Mac 上还没有设置过 bx，或者那个文件不可读。要设置：sudo bx setup <你的链接>。",
    "bx could not start: the embedded transport binary could not be unpacked into data_dir (usually a full disk or an unwritable directory).": "bx 没能启动：内嵌的传输程序没能解压到 data_dir（通常是磁盘满了或目录不可写）。",
    "bx could not start: the TUN device could not be opened (permissions, or the device is in use).": "bx 没能启动：打不开 TUN 设备（权限不够，或设备被占用）。",
    "bx could not start: the TUN came up but hijacking the default route failed.": "bx 没能启动：TUN 起来了，但接管默认路由失败了。",
    "bx could not start: Core reported a failure this version of bx has no specific wording for.": "bx 没能启动：Core 报告了一种这一版 bx 没有专门说法的失败。",
    "You also have another server configured: {0} — switch to it in Servers…": "你还配置了另一台服务器：{0} —— 可以在「服务器…」里切换过去",
    "Check it yourself: {0}": "自己检查一下：{0}",
    "bx re-checks this on every attempt and still cannot prove no second bx Core is running. Quit any sudo bx run you have open, then try again. sudo bx down then sudo bx up makes Guardian forget the judgement, but it will refuse just the same while a Core really is running — see sudo tail -50 /var/log/bx-guard.err.log for the process it found": "bx 每次尝试都会重新检查，但仍然无法证明没有第二个 bx Core 在运行。退出你开着的所有 sudo bx run，然后再试一次。先 sudo bx down 再 sudo bx up 会让 Guardian 忘掉这个判断，但只要真有一个 Core 在运行，它照样会拒绝 —— 它找到的那个进程见 sudo tail -50 /var/log/bx-guard.err.log",
    "The menu's direct call has no fallback. Run sudo bx down in Terminal (not this toggle again) — the command line forces a teardown when Guardian refuses to stop. Then try sudo bx up": "菜单的直接调用没有兜底。请在终端里运行 sudo bx down（不要再拨这个开关）—— Guardian 拒绝停止时，命令行会强制拆除。然后再试 sudo bx up",
    "Guardian is still handling the previous request — retry shortly": "Guardian 还在处理上一个请求 —— 稍后再试",
    "Failure code {0}": "失败码 {0}",
    "Guardian could not turn bx off; completed by forced teardown via sudo bx down": "Guardian 没能关掉 bx；已通过 sudo bx down 强制拆除完成",
    "Turning bx off through Guardian failed": "通过 Guardian 关闭 bx 失败",
    "{0}; sudo bx down did not complete either — run sudo bx down in Terminal yourself": "{0}；sudo bx down 也没能完成 —— 请自己在终端里运行 sudo bx down",
    "bx did not stop, so the menu stays. Quitting now would leave protection running with no indicator at all. Run sudo bx down in Terminal (it forces a teardown when Guardian refuses to stop), then click Quit bx again.": "bx 没有停下来，所以菜单留着。现在退出会让保护继续运行，却连一个指示灯都没有。请在终端里运行 sudo bx down（Guardian 拒绝停止时它会强制拆除），然后再点一次「退出 bx」。",
    "no answer (timed out)": "没有应答（超时）",
    "canceled": "已取消",
    "could not resolve that host name": "解析不了那个主机名",
    "connection refused (nothing is listening)": "连接被拒绝（那边没有程序在监听）",
    "network unreachable": "网络不可达",
    "no route to that host": "没有到那台主机的路由",
    "no host to test": "没有可测的主机",
    "the port in that link is not valid": "那条链接里的端口无效",
    "could not measure (is bx running?)": "没能测（bx 在运行吗？）",
    "could not read a host from that link": "从那条链接里读不出主机",
    "could not connect": "连不上",
    "could not measure": "没能测",
    "unreachable": "不可达",
    "in use right now": "正在使用",
    "peak {0}": "峰值 {0}",
    "not measured": "没测成",
    "not measured — {0}": "没测成 —— {0}",
    "Link could not be parsed": "链接解析不了",
    "tunnel healthy": "隧道健康",
    "tunnel unhealthy": "隧道不健康",
    "bx is actually using a different server right now.": "bx 此刻实际在用的是另一台服务器。",
    "bx is actually using {0} right now.": "bx 此刻实际在用的是 {0}。",
    "bx could not confirm which server is running.": "bx 没能确认此刻在跑的是哪一台服务器。",
    "Core not answering — the live readings below are missing.": "Core 没有应答 —— 下面缺少实时读数。",
    "Your server": "你的服务器",
    "This config has a single server, not a server list. Adding a second one turns it into a list you can switch between.": "这份配置只有一台服务器，不是服务器列表。再添加一台，它就会变成一个可以来回切换的列表。",
    "No servers yet. Add one to switch between exits.": "还没有服务器。添加一台，就可以在出口之间切换。",
    "No servers to switch to. Add another one to switch your exit between them.": "没有可切换的服务器。再添加一台，就可以在它们之间切换出口。",
    "Remove {0} from your list?": "要从列表里删除 {0} 吗？",
    "Your traffic is going through this server right now, even though your config points at another one. Removing it does not move your traffic: the running tunnel keeps using it until bx reconnects, and the link is gone by then.": "你的流量此刻正经过这台服务器，虽然配置指向的是另一台。删除它不会挪走你的流量：正在运行的隧道会一直用它，直到 bx 重新连接 —— 而那时链接已经没了。",
    "bx could not confirm which server is carrying your traffic right now, so this may be the one in use. Removing it does not move your traffic: a running tunnel keeps using it until bx reconnects, and the link is gone by then.": "bx 没能确认此刻是哪一台在承载你的流量，所以可能就是这一台。删除它不会挪走你的流量：正在运行的隧道会一直用它，直到 bx 重新连接 —— 而那时链接已经没了。",
    "Its link goes with it. bx never hands the link to this menu, so this cannot be undone from here — you would have to paste the link again.": "它的链接会一起删掉。bx 从不把链接交给这个菜单，所以这里无法撤销 —— 你得重新粘贴一次链接。",
    "That is the server your traffic uses right now. Switch to another one first, then remove this one.": "你的流量此刻正在用这台服务器。先切换到另一台，再删除这一台。",
    "That server is not in your list any more — it may already be gone.": "那台服务器已经不在列表里了 —— 可能已经被删掉了。",
    "bx could not remove that server from the config file.": "bx 没能把那台服务器从配置文件里删掉。",
    "bx could not save that link. Check that you pasted a complete bx link.": "bx 没能保存那条链接。请检查你粘贴的是不是一条完整的 bx 链接。",
    "bx could not read the config file, so nothing was changed.": "bx 读不到配置文件，所以什么都没改。",
    "Saved the new link for {0}. The tunnel that is running still uses the old address — bx picks up the new one when it reconnects.": "已保存 {0} 的新链接。正在运行的隧道仍用旧地址 —— bx 重新连接时会换成新的。",
    "Saved the new link for {0}. Your exit does not change: press Use on it when you want to switch over.": "已保存 {0} 的新链接。你的出口不变：想切换过去时，点它旁边的「使用」。",
    "Optional. A second link for UDP/QUIC traffic, if your server has one.": "可选。如果你的服务器有专门给 UDP/QUIC 流量的第二条链接，填在这里。",
    "Optional. Leave it empty to keep the UDP link this server already has, or tick the box below to remove it.": "可选。留空会保留这台服务器现有的 UDP 链接；勾选下面的框则会去掉它。",
    "Optional. Leave it empty to keep the UDP link this server already has — this version of bx cannot clear one.": "可选。留空会保留这台服务器现有的 UDP 链接 —— 这一版 bx 无法去掉它。",
    "Switch your exit to {0}?": "把出口切换到 {0}？",
    "Your public IP changes immediately. Sites you are signed in to may ask you to verify again, and downloads in flight will break.": "你的公网 IP 会立刻改变。已登录的网站可能要求你重新验证，正在进行的下载会中断。",
    "Your traffic now leaves from {0}.": "你的流量现在从 {0} 出去。",
    "Saved {0} as your server, but bx could not start the switch. Your traffic still leaves from the previous server. Turn bx off and on again to use it.": "已把 {0} 存为你的服务器，但 bx 没能开始切换。你的流量仍从原来那台出去。关掉 bx 再打开就会用上它。",
    "Saved {0} as your server, but its tunnel did not come up, so bx switched back. Your traffic still leaves from the previous server.": "已把 {0} 存为你的服务器，但它的隧道没建立起来，所以 bx 切了回去。你的流量仍从原来那台出去。",
    "Saved {0} as your server. Its tunnel did not come up and bx could not switch back, so your connection may be down right now. Run `{1}` in Terminal to recover.": "已把 {0} 存为你的服务器。它的隧道没建立起来，bx 也没能切回去，所以你的网络此刻可能是断的。在终端里运行 `{1}` 来恢复。",
    "Your traffic already leaves from {0}, but bx could not confirm the switch, so a safety timer may put it back on the previous server. Run `{1}` in Terminal now to make it stick.": "你的流量已经从 {0} 出去，但 bx 没能确认这次切换，所以一个安全定时器可能会把它切回原来那台。现在在终端里运行 `{1}`，让它固定下来。",
    "Saved {0} as your server, but bx could not tell whether the running tunnel switched. Check `bx status`; if it is still on the previous server, turn bx off and on again.": "已把 {0} 存为你的服务器，但 bx 判断不了正在运行的隧道有没有切过去。看一下 `bx status`；如果还在原来那台上，就关掉 bx 再打开。",
    "Added {0} to your servers, but could not switch to it. Open Servers… and press Use to try again.": "已把 {0} 加进你的服务器，但没能切换过去。打开「服务器…」，点「使用」再试一次。",
    "Added {0}.": "已添加 {0}。",
    "A server with that name is already in your list. Pick another name, or use it from Servers….": "列表里已经有同名的服务器了。换个名字，或者在「服务器…」里使用它。",
    "bx could not add that server. Check the link, and use only letters, digits, dots, underscores or hyphens in the name.": "bx 没能添加那台服务器。请检查链接，名字只用英文字母、数字、点、下划线或连字符。",
    "Exit IP: not checked": "出口 IP：未检查",
    "Exit IP: checking…": "出口 IP：检查中…",
    "Exit IP: could not check": "出口 IP：没能检查",
    "Exit IP: {0}": "出口 IP：{0}",
    "Exit IP: {0} — matches {1}": "出口 IP：{0} —— 与 {1} 一致",
    "{0}m ago": "{0} 分钟前",
    "{0}h ago": "{0} 小时前",
    "{0}d ago": "{0} 天前",
    "{0} will always go direct": "{0} 将总是直连",
    "{0} will always go through the tunnel": "{0} 将总是经过隧道",
    "{0}: {1}": "{0}：{1}",
    "Add": "添加",
    "Add a Routing Rule": "添加分流规则",
    "Add and Switch": "添加并切换",
    "Add Anyway": "仍然添加",
    "Add Server": "添加服务器",
    "Added": "已添加",
    "Allow bx to control Terminal when macOS asks, then try again. You can review this in System Settings > Privacy & Security > Automation.": "macOS 询问时，请允许 bx 控制「终端」，然后再试一次。你可以在「系统设置 > 隐私与安全性 > 自动化」里查看这项设置。",
    "App traffic is not available": "应用流量不可用",
    "bx applies routing rules when it reconnects. Until then, traffic keeps following the old rules.": "bx 会在重新连接时应用分流规则。在那之前，流量仍按旧规则走。",
    "bx can't run": "bx 无法运行",
    "bx could not complete the installation.": "bx 没能完成安装。",
    "bx could not complete the update.": "bx 没能完成更新。",
    "bx could not prepare its update log.": "bx 没能准备好更新日志。",
    "bx could not start the leak check. Run `bx leakcheck` in Terminal to see why.": "bx 没能启动泄漏检测。在终端里运行 `bx leakcheck` 查看原因。",
    "bx couldn't read a private gateway address for this network. Turn bx off, sign in with your browser, then turn it back on.": "bx 读不到这个网络的私网网关地址。请关闭 bx，用浏览器登录，然后再打开 bx。",
    "bx is configured, but did not start.": "bx 已配置好，但没有启动。",
    "bx is installed at {0} but could not be started. Reinstall bx from Bx.app, then try again.": "bx 安装在 {0}，但无法启动。请从 Bx.app 重新安装 bx，然后再试一次。",
    "bx is not installed at {0}. Install bx, then try again.": "{0} 没有安装 bx。请安装 bx，然后再试一次。",
    "bx is set up": "bx 已设置好",
    "bx is still running": "bx 仍在运行",
    "bx kept its previous configuration.": "bx 保留了原来的配置。",
    "bx not found": "找不到 bx",
    "bx was not configured.": "bx 没有被配置。",
    "bx will always send this domain the way you pick.": "bx 会让这个域名总是按你选的方式走。",
    "bx will install its command line tool and background protection service. macOS will ask for administrator authorization. If protection is already running, it is stopped and restarted to complete the upgrade — your network drops for a few seconds. On a fresh install, protection is not started until you set up and turn it on.": "bx 会安装它的命令行工具和后台保护服务。macOS 会要求管理员授权。如果保护已经在运行，会先停下再重新启动以完成升级 —— 网络会断几秒。全新安装时，在你设置好并打开之前，保护不会启动。",
    "bx will reinstall its components from this app. Your connection settings are kept. If protection is running, it is stopped and restarted to finish the change — your network drops for a few seconds, then protection comes back on.": "bx 会用这个 App 里的组件重新安装自己。连接设置会保留。如果保护开着，会先停下再重新启动以完成改动 —— 网络会断几秒，然后保护恢复。",
    "bx will stop protecting system traffic and restore managed DNS settings. The menu stays open.": "bx 会停止保护系统流量，并还原它接管的 DNS 设置。菜单会继续留着。",
    "bx will take over system traffic until you turn it off.": "bx 会接管系统流量，直到你关掉它。",
    "bx: {0}": "bx：{0}",
    "bx: {0}, {1}": "bx：{0}，{1}",
    "bx: Not Installed": "bx：未安装",
    "bx: Protected": "bx：受保护",
    "bx: Protected, {0} ms": "bx：受保护，{0} ms",
    "bx: Setup Required": "bx：需要设置",
    "bx: Update Required": "bx：需要更新",
    "Cancel": "取消",
    "Change where your traffic leaves?": "更改流量的出口？",
    "Check for Leaks…": "检查泄漏…",
    "Check for Problems": "检查问题",
    "Checks are not available": "检查不可用",
    "Continue": "继续",
    "Core": "Core",
    "Core status unavailable": "Core 状态不可用",
    "Core unavailable": "Core 不可用",
    "Could not add that rule": "没能添加那条规则",
    "Could not add that server": "没能添加那台服务器",
    "Could not change that group": "没能更改那一组",
    "Could not remove that rule": "没能删除那条规则",
    "Could not remove that server": "没能删除那台服务器",
    "Could not replace that link": "没能更换那条链接",
    "Could not restore that rule": "没能恢复那条规则",
    "Could not start the installer": "没能启动安装程序",
    "Could not switch server": "没能切换服务器",
    "Could not test the servers": "没能测试服务器",
    "Couldn't find this network's sign-in page": "找不到这个网络的登录页面",
    "Details": "详情",
    "e.g. tokyo": "例如 tokyo",
    "Either paste a new UDP link or tick the box to remove it — not both.": "要么粘贴一条新的 UDP 链接，要么勾选去掉它 —— 不能两样都做。",
    "Guardian": "Guardian",
    "Install": "安装",
    "Install bx": "安装 bx",
    "Install bx at /usr/local/bin/bx": "请把 bx 安装到 /usr/local/bin/bx",
    "Install bx?": "安装 bx？",
    "Install failed": "安装失败",
    "Install the macOS bx package again, or update the CLI at /usr/local/bin/bx, then restart the menu bar app.": "请重新安装 macOS 版 bx 安装包，或更新 /usr/local/bin/bx 的命令行工具，然后重启菜单栏 App。",
    "Last operation failed": "上一次操作失败",
    "Later": "稍后",
    "Leak check did not start": "泄漏检测没有启动",
    "Leave it empty to name it after the server's address.": "留空则用服务器地址作为名字。",
    "Link not recognized": "认不出这条链接",
    "Link replaced": "链接已更换",
    "Logs are not available": "日志不可用",
    "Name this server": "给这台服务器起个名字",
    "No link": "没有链接",
    "Not Installed": "未安装",
    "Not Now": "以后再说",
    "Open Install Guide": "打开安装指南",
    "Open Logs": "打开日志",
    "Open Wi-Fi Sign-In Page": "打开 Wi-Fi 登录页面",
    "Paste a bx link to continue.": "请粘贴一条 bx 链接以继续。",
    "Paste a bx link, or leave the second box empty.": "请粘贴一条 bx 链接，或者让第二个框空着。",
    "Paste a bx link, or the whole setup command your server printed, to continue.": "请粘贴一条 bx 链接，或服务器打印出来的整条设置命令，以继续。",
    "Paste the bx link for the new server. It will be added to your list and used right away.": "粘贴新服务器的 bx 链接。它会被加进你的列表并立即启用。",
    "Paste the bx link you were given, or the whole setup command your server printed.": "粘贴你拿到的 bx 链接，或服务器打印出来的整条设置命令。",
    "Paste the new bx link for {0}. Nothing else about this server changes, and your exit stays where it is.": "粘贴 {0} 的新 bx 链接。这台服务器的其他设置都不变，你的出口也保持不变。",
    "Paste your bx link, or the whole setup command your server printed.": "粘贴你的 bx 链接，或服务器打印出来的整条设置命令。",
    "Quit bx": "退出 bx",
    "Quit bx?": "退出 bx？",
    "Reconnect": "重新连接",
    "Reconnect failed": "重连失败",
    "Reconnect Now": "立即重连",
    "Recovery: {0}": "恢复：{0}",
    "Remove server?": "删除服务器？",
    "Remove this server's UDP link": "去掉这台服务器的 UDP 链接",
    "Repair": "修复",
    "Repair bx?": "修复 bx？",
    "Repair Required": "需要修复",
    "Replace": "更换",
    "Replace Configuration": "更换配置",
    "Replace Configuration…": "更换配置…",
    "Replace failed": "更换失败",
    "Replace Link": "更换链接",
    "Routing Rules…": "分流规则…",
    "Routing rules are not available": "分流规则不可用",
    "Run Doctor to collect diagnostics.": "运行诊断以收集诊断信息。",
    "Run sudo bx setup <client-link>": "请运行 sudo bx setup <客户端链接>",
    "Runtime": "运行时",
    "Saved, but not applied yet": "已保存，但还没生效",
    "Servers…": "服务器…",
    "Servers are not available": "服务器列表不可用",
    "Set Up": "设置",
    "Set Up bx": "设置 bx",
    "Set Up bx...": "设置 bx…",
    "Setup failed": "设置失败",
    "Setup Required": "需要设置",
    "Show Details": "显示详情",
    "Stage: {0}": "阶段：{0}",
    "Start failed": "启动失败",
    "Start Protection": "开始保护",
    "Start protection?": "开始保护？",
    "Status": "状态",
    "Status unreadable": "读不懂状态",
    "Switch": "切换",
    "Switch server?": "切换服务器？",
    "Switched": "已切换",
    "Terminal permission needed": "需要「终端」权限",
    "Testing needs bx to be running: it measures from outside the tunnel, which only bx itself can do.": "测试需要 bx 在运行：它要在隧道之外测量，而这只有 bx 自己做得到。",
    "The bx background service that is running does not handle changes to the server list. It may have been replaced on disk without being restarted. Reopen this window after turning protection off and on again.": "正在运行的 bx 后台服务不支持修改服务器列表。它可能在磁盘上被替换了却没有重启。请把保护关掉再打开，然后重新打开这个窗口。",
    "The change is already in effect. New connections follow the new rules.": "改动已经生效，新的连接会按新规则走。",
    "The new configuration is saved, but bx did not come back up. Try Turn On from the menu.": "新配置已保存，但 bx 没能重新启动。试试从菜单里打开保护。",
    "This can take a few minutes on a slow connection.": "网络慢的话可能要几分钟。",
    "This copy of Bx.app has no embedded installer. Download the full bx-macos package.": "这份 Bx.app 里没有内置安装程序。请下载完整的 bx-macos 安装包。",
    "Through tunnel": "经过隧道",
    "Traffic by App…": "按应用查看流量…",
    "Troubleshoot": "故障排查",
    "Turn Off": "关闭",
    "Turn off bx?": "关闭 bx？",
    "Turned off {0}": "已关闭 {0}",
    "Turned on {0}": "已开启 {0}",
    "Two answers for UDP": "UDP 设置自相矛盾",
    "UDP link (optional)": "UDP 链接（可选）",
    "UDP link not recognized": "认不出 UDP 链接",
    "Update": "更新",
    "Update complete": "更新完成",
    "Update failed": "更新失败",
    "Update Required": "需要更新",
    "Update rolled back": "更新已回滚",
    "Updating bx": "正在更新 bx",
    "Version": "版本",
    "You can run this yourself in Terminal:": "你可以自己在终端里运行：",
    "Language": "语言",
    "Guardian DNS": "Guardian 的 DNS",
    "Guardian installed": "Guardian 已安装",
    "Service installed": "服务已安装",
    "Service enabled": "服务已启用",
    "Service active": "服务在运行",
    "Config": "配置",
    "Config readable": "配置可读",
    "Config parse": "配置解析",
    "Config permissions": "配置文件权限",
    "Server link": "服务器链接",
    "Transports": "传输",
    "Status socket": "状态 socket",
    "UDP policy": "UDP 策略",
    "UDP transport": "UDP 传输",
    "UDP traffic": "UDP 流量",
    "Network recovery": "网络恢复",
    "Traffic failing rules": "正在失败的规则",
    "Traffic outcomes": "流量成败",
    "Direct egress": "直连出口",
    "Tunnel": "隧道",
    "Probe": "探测",
    "Desired off": "保护被设为关闭",
    "Failing rules": "正在失败的规则",
    "Terminal proxy": "终端代理",
    "Tunnel claims": "其他隧道占用",
    "Permission fallback": "权限回退",
    "bx could not read its logs: {0}": "bx 读不到它的日志：{0}",
    "bx could not run its checks: {0}": "bx 没能运行检查：{0}",
]
